// import type { NextPage } from "next";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";

import Head from "next/head";
import { NextPage } from "next";
import { trpc } from "~/utils/trpc";
import { DefaultLayout } from "~/components/DefaultLayout";
import { useSession, signIn, signOut } from "next-auth/react";

// import { TestDOM } from "~/components/Test";
// import "../../styles/globals.css";

const Home: NextPage = () => {
  // const word = trpc.useQuery([
  //   "wordCard.allVoc",
  //   {
  //     userId: 1,
  //   },
  // ]);

  // const user = trpc.useQuery([
  //   "user.get",
  //   {
  //     email: "kk297466058@gmail.com",
  //   },
  // ]);

  // console.log(user.data);
  // console.log(word.data);
  //   const userInfo = trpc.useQuery([
  //     "userInfo.get",
  //     {
  //       email: "kk297466058@gmail.com",
  //     },
  //   ]);

  //   if (!hello.data) {
  //     return <div>Loading...</div>;
  //   }

  //   const user = userInfo.data ?? undefined;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-3xl font-bold underline">
        <p className="underline decoration-sky-500 text-ellipsis">
          asdfasdjflj
        </p>
        {/* <>
          Not signed in <br />
          <button onClick={() => signIn()}>Sign in</button>
        </> */}
        <DefaultLayout>kanban</DefaultLayout>
      </main>
    </div>
  );
};

export default Home;
